import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Card, CardContent } from "./_components/ui/card";
import Contacts from "./_components/ui/contacts";
import { db } from "./_lib/prisma";

const CommerceContacts = await db.commerce.findUnique({
  where: { id: "4f7ce77f-94d5-4e03-b05f-1d62d810e227" },
  select: {
    phones: true,
    instagram: true,
  },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR" className="dark">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        

      </body>
    </html>
  );
}
